"""add interval to simulation_sessions

Revision ID: 90126ec99a1c
Revises: a0ade0f6e417
Create Date: 2026-02-08 22:26:52.323386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90126ec99a1c'
down_revision: Union[str, Sequence[str], None] = 'a0ade0f6e417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_sessions', sa.Column('interval', sa.String(length=10), nullable=False, server_default='1d'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_sessions', 'interval')
    # ### end Alembic commands ###
