"""add fee columns

Revision ID: a0ade0f6e417
Revises: fb5dcf30fb9e
Create Date: 2026-02-08 22:17:43.880791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ade0f6e417'
down_revision: Union[str, Sequence[str], None] = 'fb5dcf30fb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_sessions', sa.Column('trading_fee_pct', sa.Numeric(precision=6, scale=2), nullable=False, server_default='1.0'))
    op.add_column('simulation_trades', sa.Column('fee', sa.Numeric(precision=12, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_trades', 'fee')
    op.drop_column('simulation_sessions', 'trading_fee_pct')
    # ### end Alembic commands ###
